### ISSUE TITLE
thanks , but have a bug

### ISSUE THREAD

**Issue by janfeng** [korobochkin/bbpress-permalinks-with-id#1]
can't edit the reply , can u fix ?

**Comment by korobochkin** [comment]
Finally I fixed this bug. bbPress source code like a labyrinth, but now it works fine: editing and viewing with all permalink setups:
- site.com/forums/forum/ID/[edit]
- site.com/forums/topic/ID/[edit]
- site.com/?post_type=forum&p=ID[&edit=1] (strange but &forum=forum-slug adds automatically)
- site.com/?post_type=topic&p=ID[&edit=1] (strange but &topic=topic-slug adds automatically)

https://github.com/korobochkin/bbPress-permalinks-with-id/commit/5396cfa11663fdce9f6387ae5c443db108a4bda4
